# A string used to differentiate different projects.
project_id = "bookamplify"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[ingest]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation_enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true

[analytics]
enabled = false

[functions]
enabled = false
